---
services:
  postgres-api:
    container_name: postgres-api
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - "6001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - random_data_api_network

  random-data-api:
    container_name: random-data-api
    env_file:
      - ./docker/.env
    build: 
      context: .
      dockerfile: docker/Dockerfile
      args:
        GO_VERSION: ${GO_VERSION}
        BUILD_VERSION: ${BUILD_VERSION}
    restart: unless-stopped
    ports:
      - "8080:9909"
    depends_on:
      - postgres-api
    networks:
      - random_data_api_network

volumes:
  postgres_data:

networks:
  random_data_api_network:
    driver: bridge
